server:
  port:
    9000

spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/sampleairbnb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql : true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  jackson:
    property-naming-strategy: SNAKE_CASE

  jwt:
    secret-key: SECRET_KEY